<?=\Bugloos\CustomFramework\Helper\View::render("common/header",["title"=>"contact"])?>
<div class="container">
    <?=\Bugloos\CustomFramework\Helper\View::render("common/errors",[])?>
    <div class="row">
        <div class="col-md-8">
            <form method="post" action="/contact" novalidate>
                <div class="form-group" >
                    <label for="name">Name</label>
                    <input type="text" class="form-control" id="name" name="name">
                </div>
                <div class="form-group">
                    <label for="last-name">Last name</label>
                    <input type="text" class="form-control"  id="last-name" name="lastname">
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" class="form-control"  id="email" name="email">
                </div>
                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea  id="description" class="form-control"  name="description"></textarea>
                </div>
                <button type="submit" class="btn btn-success">Send</button>
            </form>
        </div>
        <div class="col-md-4">
            name: <?=$name?><br>
            address: <?=$address?>
        </div>
    </div>
</div>